// cache.js
import Redis from "ioredis";
import { promisify } from "util";

export function createCache(redisUrl) {
  const client = new Redis(redisUrl);

  // middleware: checks cache by key (generated by handler)
  function cacheMiddleware(getKey, ttlSeconds = 60) {
    return async (req, res, next) => {
      try {
        const key = await getKey(req);
        if (!key) return next();
        const cached = await client.get(key);
        if (cached) {
          res.setHeader("X-Cache", "HIT");
          return res.json(JSON.parse(cached));
        }
        // store key / ttl on res so route handler can set cache after fetching
        res.locals.cache = { client, key, ttlSeconds };
        res.setHeader("X-Cache", "MISS");
        next();
      } catch (err) {
        // on errors, skip caching but continue
        next();
      }
    };
  }

  // helper to set cache (call from route)
  async function setCache(key, value, ttlSeconds) {
    if (!key) return;
    await client.set(key, JSON.stringify(value), "EX", ttlSeconds);
  }

  return { client, cacheMiddleware, setCache };
}
